apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: frontend
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch
        Match   *
        region ap-south-1
        log_group_name fargate-logs
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name json
        Format json

